using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.SqlClient;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Diagnostics;
using DevExpress.XtraBars.Customization.Helpers;
using DevExpress.XtraEditors;

namespace ETravUpdater
{
    public partial class Form1 : DevExpress.XtraEditors.XtraForm
    {
        string xfile;
        string fn;
        string[] versioninfo;
        string FileNameof;
        String ConnStr = "Data Source=etrav-hack;Initial Catalog=Images;Persist Security Info=True;User ID=Application;Password=noitacilppa";
        public Assembly a;
        public string id;
        string version;
        string Locations = "Default Location";
        bool updateRequest = false;
        private bool dllbtn;
        private bool frf3btn;
        private bool inibtn;
        private bool xmlbtn;
        SimpleButton currentEditor;
        private bool frfbtn;

        public bool exebtn { get; private set; }

        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            timer1.Tick += new EventHandler(timer1_Tick);
            timer1.Interval = 500;
            timer1.Enabled = true;
            currentEditor = simpleButton1;
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (checkButton1.Checked)
            {
                simpleButton1.Appearance.BackColor = Color.LightGreen;
                simpleButton1.Appearance.BackColor2 = Color.DarkGreen;
                timer1.Start();

            }
           
            DialogResult result = openFileDialog1.ShowDialog();
            if (result == DialogResult.OK) // Test result.
            {
                xfile = openFileDialog1.FileName;
                FileNameof = Path.GetFileName(xfile);
                fn = Path.GetFileNameWithoutExtension(xfile);
                if (exebtn == true || dllbtn == true)
                {
                    try
                    {
                        System.Reflection.AssemblyName testAssembly =
                System.Reflection.AssemblyName.GetAssemblyName(@xfile);
                    }
                    catch(System.BadImageFormatException)
                    {
                        System.Console.WriteLine("The file is not an assembly.");
                        MessageBox.Show("The file selected is not an exe or dll");
                        return;
                    }
                        
               }

                var assembly = a = Assembly.LoadFile(xfile);  //typeof(Program).Assembly;
                var attribute = (GuidAttribute)assembly.GetCustomAttributes(typeof(GuidAttribute), true)[0];
                id = attribute.Value;
                FileVersionInfo fvi = FileVersionInfo.GetVersionInfo(assembly.Location);
                version = fvi.FileVersion;
                versioninfo = fvi.FileVersion.Split('_');
                Version v;
                if (versioninfo.Length > 1 && Version.TryParse(versioninfo.Last(), out v))
                {
                    Console.Write("Major:{0}, Minor:{1}", v.Major, v.Minor);
                }
                databaseFileRead(id, version);

                if (updateRequest == true)
                {
                    databaseFileupdate(xfile, version);
                }
                if (updateRequest != true)
                {
                    databaseFilePut(xfile);
                }

            }
            Console.WriteLine(result); // <-- For debugging use.
        }

        public  void databaseFilePut(string varFilePath) //Puts any file on server!
        {
            byte[] file;
            using (var stream = new FileStream(varFilePath, FileMode.Open, FileAccess.Read))
            {
                using (var reader = new BinaryReader(stream))
                {
                    file = reader.ReadBytes((int)stream.Length);
                }
            }
            using (SqlConnection SqlConn = new SqlConnection(ConnStr))
            using (SqlCommand command = SqlConn.CreateCommand())
            {
                command.CommandText = "INSERT INTO tblVSapplications (VSApplication, FileVersion, DefaultLocation, FileDate, Applicationguid, Applicationname) VALUES (@binapp, @versioninfo, " + "'" + Locations + "'" + ",getdate()," + "'" + id + "'," + "'" + FileNameof + "')";
                //command.CommandText = "UPDATE tblVSapplications SET VSApplication=@binapp, FileVersion=@versioninfo, DefaultLocation= " + "'" + Locations + "'" + ",FileDate=getdate(), Applicationguid=" + "'" + id + "'" + ",Applicationname=" + "'" + FileNameof + "'";
                command.Parameters.AddWithValue("@binapp", file);
                command.Parameters.AddWithValue("@versioninfo", version);

                SqlConn.Open();

                command.ExecuteNonQuery();
                
                SqlConn.Close();
                // This line of code is generated by Data Source Configuration Wizard
                // Fill a SqlDataSource
                sqlDataSource1.Fill();
                // This line of code is generated by Data Source Configuration Wizard
                // Fill a SqlDataSource
                sqlDataSource1.Fill();
                timer1.Stop();
            }
        }

        public void databaseFileupdate(string varFilePath,string version) //Updates any file on server!
        {
            byte[] file;
            using (var stream = new FileStream(varFilePath, FileMode.Open, FileAccess.Read))
            {
                using (var reader = new BinaryReader(stream))
                {
                    file = reader.ReadBytes((int)stream.Length);
                }
            }
            using (SqlConnection SqlConn = new SqlConnection(ConnStr))
            using (SqlCommand command = SqlConn.CreateCommand())
            {
                //command.CommandText = "INSERT INTO tblVSapplications (VSApplication, FileVersion, DefaultLocation, FileDate, Applicationguid, Applicationname) VALUES (@binapp, @versioninfo, " + "'" + Locations + "'" + ",getdate()," + "'" + id + "'," + "'" + FileNameof + "')";
                command.CommandText = "UPDATE tblVSapplications SET VSApplication=@binapp, FileVersion=@versioninfo,FileDate=getdate() WHERE Applicationname=" + "'" + FileNameof + "'";
                command.Parameters.AddWithValue("@binapp", file);
                command.Parameters.AddWithValue("@versioninfo", version);

                SqlConn.Open();

                command.ExecuteNonQuery();

                SqlConn.Close();
                // This line of code is generated by Data Source Configuration Wizard
                // Fill a SqlDataSource
                sqlDataSource1.Fill();
                // This line of code is generated by Data Source Configuration Wizard
                // Fill a SqlDataSource
                sqlDataSource1.Fill();
                timer1.Stop();
            }
        }

        public void databaseFileRead(string varID, string version) //Just reads file on server for comparison
        {
            using (SqlConnection SqlConn = new SqlConnection(ConnStr))
            using (SqlCommand command = SqlConn.CreateCommand())
            {
                SqlConn.Open();
                //varPathToNewLocation = xfile;
                command.Parameters.AddWithValue("@varID", varID);
                command.CommandText = "SELECT VSApplication FROM tblVSapplications WHERE Applicationguid='"+ varID + "'";
                using (var sqlQueryResult = command.ExecuteReader())
                    if (sqlQueryResult != null)
                    {
                        //sqlQueryResult.Read();
                       // var blob = new Byte[(sqlQueryResult.GetBytes(0, 0, null, 0, int.MaxValue))];
                       // sqlQueryResult.GetBytes(0, 0, blob, 0, blob.Length);
                       // using (var fs = new FileStream(varPathToNewLocation, FileMode.Create, FileAccess.Write))
                            //fs.Write(blob, 0, blob.Length);
                        updateRequest = true;
                    }
                SqlConn.Close();
            }
        }

        public MemoryStream databaseFileRead(string varID)
        {
            MemoryStream memoryStream = new MemoryStream();
            using (SqlConnection SqlConn = new SqlConnection(ConnStr))
            using (SqlCommand command = SqlConn.CreateCommand())
            {
                command.CommandText = @"SELECT [Application] FROM tblapplications WHERE [RaportID] = @varID";
                command.Parameters.AddWithValue("@varID", varID);
                using (var sqlQueryResult = command.ExecuteReader())
                    if (sqlQueryResult != null)
                    {
                        sqlQueryResult.Read();
                        var blob = new Byte[(sqlQueryResult.GetBytes(0, 0, null, 0, int.MaxValue))];
                        sqlQueryResult.GetBytes(0, 0, blob, 0, blob.Length);
                        //using (var fs = new MemoryStream(memoryStream, FileMode.Create, FileAccess.Write)) {
                        memoryStream.Write(blob, 0, blob.Length);
                        //}
                    }
            }
            return memoryStream;
        }

        public int databaseFilePut(MemoryStream fileToPut)
        {
            int varID = 0;
            byte[] file = fileToPut.ToArray();
            const string preparedCommand = @"
                    INSERT INTO tblapplications
                               ([RaportPlik])
                         VALUES
                               (@File)
                        SELECT [RaportID] FROM [dbo].[Raporty]
            WHERE [RaportID] = SCOPE_IDENTITY()
                    ";
            using (SqlConnection SqlConn = new SqlConnection(ConnStr))
            using (SqlCommand command = SqlConn.CreateCommand())
            {
                command.Parameters.Add("@File", SqlDbType.VarBinary, file.Length).Value = file;

                using (var sqlWriteQuery = command.ExecuteReader())
                    while (sqlWriteQuery != null && sqlWriteQuery.Read())
                    {
                        varID = sqlWriteQuery["RaportID"] is int ? (int)sqlWriteQuery["RaportID"] : 0;
                    }
            }
            return varID;
        }

        private void dropDownButton1_Click(object sender, EventArgs e)
        {

        }

        private void dropDownButton2_Click(object sender, EventArgs e)
        {

        }

        private void gridControl2_Click(object sender, EventArgs e)
        {

        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();

        }

        private void checkButton1_CheckedChanged(object sender, EventArgs e) //exe
        {
            
            if (checkButton1.Checked)
            {
                checkButton1.Appearance.BackColor = Color.LightGreen;
                checkButton1.Appearance.BackColor2 = Color.DarkGreen;
                exebtn = true;
            }
            else
            {
                checkButton1.Appearance.BackColor = Color.LightBlue;
                checkButton1.Appearance.BackColor2 = Color.DarkBlue;
            }
        }

        private void checkButton2_CheckedChanged(object sender, EventArgs e) //dll
        {
            if (checkButton2.Checked)
            {
                checkButton2.Appearance.BackColor = Color.LightGreen;
                checkButton2.Appearance.BackColor2 = Color.DarkGreen;
                dllbtn = true;
            }
            else
            {
                checkButton2.Appearance.BackColor = Color.LightBlue;
                checkButton2.Appearance.BackColor2 = Color.DarkBlue;
            }
        }

        private void checkButton3_CheckedChanged(object sender, EventArgs e)
        {
            if (checkButton3.Checked)
            {
                checkButton3.Appearance.BackColor = Color.LightGreen;
                checkButton3.Appearance.BackColor2 = Color.DarkGreen;
                frfbtn = true;
            }
            else
            {
                checkButton3.Appearance.BackColor = Color.LightBlue;
                checkButton3.Appearance.BackColor2 = Color.DarkBlue;
            }
        }

        private void checkButton4_CheckedChanged(object sender, EventArgs e)
        {
            if (checkButton4.Checked)
            {
                checkButton4.Appearance.BackColor = Color.LightGreen;
                checkButton4.Appearance.BackColor2 = Color.DarkGreen;
                frf3btn = true;
            }
            else
            {
                checkButton4.Appearance.BackColor = Color.LightBlue;
                checkButton4.Appearance.BackColor2 = Color.DarkBlue;
            }
        }

        private void checkButton5_CheckedChanged(object sender, EventArgs e)
        {
            if (checkButton5.Checked)
            {
                checkButton5.Appearance.BackColor = Color.LightGreen;
                checkButton5.Appearance.BackColor2 = Color.DarkGreen;
                inibtn = true;
            }
            else
            {
                checkButton5.Appearance.BackColor = Color.LightBlue;
                checkButton5.Appearance.BackColor2 = Color.DarkBlue;
            }
        }

        private void checkButton6_CheckedChanged(object sender, EventArgs e)
        {
            if (checkButton6.Checked)
            {
                checkButton6.Appearance.BackColor = Color.LightGreen;
                checkButton6.Appearance.BackColor2 = Color.DarkGreen;
                xmlbtn = true;
            }
            else
            {
                checkButton6.Appearance.BackColor = Color.LightBlue;
                checkButton6.Appearance.BackColor2 = Color.DarkBlue;
            }
        }

        private void SetControlBackColor(Color color)
        {
            if (currentEditor is SimpleButton)
            {
                ((SimpleButton)currentEditor).Appearance.BackColor = color;
                ((SimpleButton)currentEditor).Refresh();
            }
        }

        private void timer1_Tick(object sender, EventArgs e)
        {
            if (simpleButton1.Appearance.BackColor == Color.Red)
            {
                SetControlBackColor(Color.Blue);
            }
            else
            {
                SetControlBackColor(Color.Red);
            }
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            databaseFileupdate(xfile, version);
        }
    }
}
