using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.SqlClient;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Diagnostics;

namespace ETravUpdater
{
    public partial class Form1 : DevExpress.XtraEditors.XtraForm
    {
        string xfile;
        string fn;
        string[] versioninfo;
        string FileNameof;
        String ConnStr = "Data Source=etrav-hack;Initial Catalog=Images;Persist Security Info=True;User ID=Application;Password=noitacilppa";
        public Assembly a;
        public string id;
        string version;
        string Locations = "Default Location";
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            DialogResult result = openFileDialog1.ShowDialog();
            if (result == DialogResult.OK) // Test result.
            {
                xfile = openFileDialog1.FileName;
                FileNameof = Path.GetFileName(xfile);
                fn = Path.GetFileNameWithoutExtension(xfile);
                //Assembly a = Assembly.Load(fn);
                //Type myType = a.GetType(fn);
                // MethodInfo myMethod = myType.GetMethod(fn);
                //Assembly assembly = GetSatelliteAssembly();
                var assembly = a = Assembly.LoadFile(xfile);  //typeof(Program).Assembly;
                var attribute = (GuidAttribute)assembly.GetCustomAttributes(typeof(GuidAttribute), true)[0];
                id = attribute.Value;
                FileVersionInfo fvi = FileVersionInfo.GetVersionInfo(assembly.Location);
                version = fvi.FileVersion;
                versioninfo = fvi.FileVersion.Split('_');
                Version v;
                if (versioninfo.Length > 1 && Version.TryParse(versioninfo.Last(), out v))
                {
                    Console.Write("Major:{0}, Minor:{1}", v.Major, v.Minor);
                }
                databaseFilePut(xfile);
               

            }
            Console.WriteLine(result); // <-- For debugging use.
        }

        public  void databaseFilePut(string varFilePath) //Puts any file on server!
        {
            byte[] file;
            using (var stream = new FileStream(varFilePath, FileMode.Open, FileAccess.Read))
            {
                using (var reader = new BinaryReader(stream))
                {
                    file = reader.ReadBytes((int)stream.Length);
                }
            }
            using (SqlConnection SqlConn = new SqlConnection(ConnStr))
            using (SqlCommand command = SqlConn.CreateCommand())
            {
                command.CommandText = "INSERT INTO tblVSapplications (VSApplication, FileVersion, DefaultLocation, FileDate, Applicationguid, Applicationname) VALUES (@binapp, @versioninfo, " + "'" + Locations + "'" + ",getdate()," + "'" + id + "'," + "'" + FileNameof + "')";
                //command.CommandText = "UPDATE tblVSapplications SET VSApplication=@binapp, FileVersion=@versioninfo, DefaultLocation= " + "'" + Locations + "'" + ",FileDate=getdate(), Applicationguid=" + "'" + id + "'" + ",Applicationname=" + "'" + FileNameof + "'";
                command.Parameters.AddWithValue("@binapp", file);
                command.Parameters.AddWithValue("@versioninfo", version);

                SqlConn.Open();

                command.ExecuteNonQuery();
                
                SqlConn.Close();
            }
        }

        public void databaseFileRead(string varID, string varPathToNewLocation) //Just reads file on server for comparison
        {
            using (SqlConnection SqlConn = new SqlConnection(ConnStr))
            using (SqlCommand command = SqlConn.CreateCommand())
            {
                varPathToNewLocation = xfile;
                command.Parameters.AddWithValue("@varID", varID);
                command.CommandText = "SELECT * FROM tblVSapplications WHERE Applicationguid=" + varID;
                using (var sqlQueryResult = command.ExecuteReader())
                    if (sqlQueryResult != null)
                    {
                        sqlQueryResult.Read();
                        var blob = new Byte[(sqlQueryResult.GetBytes(0, 0, null, 0, int.MaxValue))];
                        sqlQueryResult.GetBytes(0, 0, blob, 0, blob.Length);
                        using (var fs = new FileStream(varPathToNewLocation, FileMode.Create, FileAccess.Write))
                            fs.Write(blob, 0, blob.Length);
                    }
            }
        }

        public MemoryStream databaseFileRead(string varID)
        {
            MemoryStream memoryStream = new MemoryStream();
            using (SqlConnection SqlConn = new SqlConnection(ConnStr))
            using (SqlCommand command = SqlConn.CreateCommand())
            {
                command.CommandText = @"SELECT [Application] FROM tblapplications WHERE [RaportID] = @varID";
                command.Parameters.AddWithValue("@varID", varID);
                using (var sqlQueryResult = command.ExecuteReader())
                    if (sqlQueryResult != null)
                    {
                        sqlQueryResult.Read();
                        var blob = new Byte[(sqlQueryResult.GetBytes(0, 0, null, 0, int.MaxValue))];
                        sqlQueryResult.GetBytes(0, 0, blob, 0, blob.Length);
                        //using (var fs = new MemoryStream(memoryStream, FileMode.Create, FileAccess.Write)) {
                        memoryStream.Write(blob, 0, blob.Length);
                        //}
                    }
            }
            return memoryStream;
        }

        public int databaseFilePut(MemoryStream fileToPut)
        {
            int varID = 0;
            byte[] file = fileToPut.ToArray();
            const string preparedCommand = @"
                    INSERT INTO tblapplications
                               ([RaportPlik])
                         VALUES
                               (@File)
                        SELECT [RaportID] FROM [dbo].[Raporty]
            WHERE [RaportID] = SCOPE_IDENTITY()
                    ";
            using (SqlConnection SqlConn = new SqlConnection(ConnStr))
            using (SqlCommand command = SqlConn.CreateCommand())
            {
                command.Parameters.Add("@File", SqlDbType.VarBinary, file.Length).Value = file;

                using (var sqlWriteQuery = command.ExecuteReader())
                    while (sqlWriteQuery != null && sqlWriteQuery.Read())
                    {
                        varID = sqlWriteQuery["RaportID"] is int ? (int)sqlWriteQuery["RaportID"] : 0;
                    }
            }
            return varID;
        }
    }
}
